### ISSUE TITLE
No funciona.

### ISSUE THREAD

**Issue by Lorengamboa** [jorgecasar/emtmadrid-lib#1]
Buenas,
probé la librería y no funciona.
He probado usar la oficial a través de postman y tampoco me funciona.

Las APIs me las enviaron esta tarde EMT.

No se si sabes que puede pasar porque desde luego la API oficial deja mucho que desear y no hay manera de debuggear lo que esta pasando.

**Comment by jorgecasar** [comment]
Buenas,

Acabo de probar la librería y funciona. Si no te funcionaba la API con postman es que estaría caído el servicio y por lo tanto la mía tampoco funciona puesto que simplemente es un wrapper de la suya para facilitar un poco su uso.

Si quieres para probar la librería puedes usar [emtmadrid-cli](https://github.com/jorgecasar/emtmadrid-cli) que es la librería con interfaz en línea de comandos.

**Comment by Lorengamboa** [comment]
Ya averigüe a que se debía pero mil gracias por contestar! No era problema de la librería que hicistes!

De todas maneras hice yo una, te invito a probarla y estas mas que invitado a colaborar.

Un saludo
